version: '2'

services:

  zookeeper0:
    extends:
      file:   base/docker-compose-base.yaml
      service: zookeeper0
    container_name: zookeeper0
  
  zookeeper1:
    extends:
      file:   base/docker-compose-base.yaml
      service: zookeeper1
    container_name: zookeeper1
    depends_on:
      - zookeeper0

  zookeeper2:
    extends:
      file:   base/docker-compose-base.yaml
      service: zookeeper2
    container_name: zookeeper2
    depends_on:
      - zookeeper0
      - zookeeper1

  kafka0:
    extends:
      file:   base/docker-compose-base.yaml
      service: kafka0
    container_name: kafka0
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    extends:
      file:   base/docker-compose-base.yaml
      service: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    extends:
      file:   base/docker-compose-base.yaml
      service: kafka2
    container_name: kafka2
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
  
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/9d03a8b7a494d873f27c3e22dc55a4a133c6bd6a91b01d40bc39a655eefd5edf_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9d03a8b7a494d873f27c3e22dc55a4a133c6bd6a91b01d40bc39a655eefd5edf_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c1267d5f9ff36b579fa41db84d3910ec802762d22eb0fcd5f85431f964a6b808_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c1267d5f9ff36b579fa41db84d3910ec802762d22eb0fcd5f85431f964a6b808_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2

  orderer0.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.example.com
    container_name: orderer0.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2

  orderer1.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.example.com
    container_name: orderer1.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2

  orderer2.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer2.example.com
    container_name: orderer2.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2

  couchdb0:
    container_name: couchdb0
    extends:
      file:  base/docker-compose-base.yaml
      service: couchdb0

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com
    depends_on:
      - couchdb0
   
  couchdb1:
    container_name: couchdb1
    extends:
      file:  base/docker-compose-base.yaml
      service: couchdb1

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.example.com
    depends_on:
      - couchdb1
  
  couchdb2:
    container_name: couchdb2
    extends:
      file:  base/docker-compose-base.yaml
      service: couchdb2

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.example.com
    depends_on:
      - couchdb2

  couchdb3:
    container_name: couchdb3
    extends:
      file:  base/docker-compose-base.yaml
      service: couchdb3

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.example.com
    depends_on:
      - couchdb3
